### ISSUE TITLE
How to test it in windows

### ISSUE THREAD

**Issue by Rohitbehera** [izderadicka/adecaptcha#2]
Hi izderadicka
 It is so good to see such invension on decode audio captcha but what if i want to test it in window can you provide steps for it

**Comment by izderadicka** [comment]
Never tested under windows and do not plan to.  On Windows you are on your own. It's using numpy and scipy and cython but should this should not be problem - these should work under win. You will also  need to compile libsvn - check their docs.  Tool to create training data uses PyQt4 - not sure how this is supported on win - probably yes.
I have to admit my code is bit messy - I never planed this as a ready product, rather it was a space for experiments in  decoding audio captchas in python. So I did not care at all about code portability.
